import styles from './Layout.module.css';
import Head from 'next/head';

const Layout = ({ children }) => {
  return (
    <>
      <Head>
        <title>Weather app</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='favicon.png' />
      </Head>

      <main className={styles.main}>{children}</main>
    </>
  );
};

export default Layout;
